# Generated by Django 3.2 on 2022-10-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0018_auto_20220722_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('fee', models.IntegerField()),
                ('map_address', models.URLField()),
                ('website', models.URLField()),
                ('content', models.TextField()),
                ('affiliated', models.CharField(max_length=80)),
            ],
        ),
    ]
