# Generated by Django 3.2 on 2022-10-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0019_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='affiliated',
            field=models.CharField(choices=[('Tribhuvan University', 'Tribhuvan University'), ('Kathmandu University', 'Kathmandu University'), ('Pokhara University', 'Pokhara University')], default='Tribhuvan University', max_length=80),
        ),
    ]
