# Generated by Django 3.2 on 2022-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0020_alter_college_affiliated'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='phn_one',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='phn_two',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
