# Generated by Django 3.2 on 2022-12-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0021_auto_20221026_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='csit.semester'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='labMarks',
            field=models.CharField(blank=True, default='20', max_length=90, null=True),
        ),
    ]
